import './globals.css'
import { Work_Sans } from 'next/font/google'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'


const inter = Work_Sans({
  weight: "400",
  subsets: ["latin"]
})

export const metadata = {
  title: 'CineChronicle',
  description: 'Generated by create next appExplore the world of cinema like never before. Dive into captivating film synopses, reviews, and behind-the-scenes insights. Discover a curated collection of movies across genres, from classics to the latest releases. Your ultimate destination for all things cinematic.',
  keywords: "films, movies, cinema, synopses, reviews, classics, latest releases, cinematic guide"
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
